services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - ./tests/testdata/keycloak:/opt/keycloak/data/import
    command: "start-dev --import-realm"
    ports:
      - "8080:8080"
